version: "3.8"
services:
  mqtt-broker-2:
    #container_name: deploy-mqtt-gateway-broker-1
    build: ./mqtt_gateway_broker/
    ports:
        - "1884:1883"
        - "9002:9001"
        - "18084:18083"
        - "4370:4369"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

  filebeat:
    #build: ./filebeat/
    image: docker.elastic.co/beats/filebeat:7.15.1
    user: root
    networks:
      - backend_backend
    #if we use docker container logs
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  vol-emqx-data:
    name: bar-emqx-data
  vol-emqx-etc:
    name: bar-emqx-etc
  vol-emqx-log:
    name: bar-emqx-log

networks:
  backend_backend:
    external: true