openapi: 3.0.0
info:
  description: Door Lock Cloud API
  version: 1.0.0
  title: Swagger REST API
paths:
  /doorlocks/{site_id}:
    get:
      operationId: "api.doorlocks.get_all_from_site"
      tags:
        - "Door Locks Site"
      summary: "All the available door locks"
      description: "Get the list of available door locks and its status."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successful get doorlocks operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  properties:
                    deviceId:
                      type: integer
                    doorState:
                      type: string
                    lockState:
                      type: string

  /doorlocks/{site_id}/{device_id}:
    get:
      operationId: "api.doorlocks.get_device_from_site"
      tags:
        - "Door Locks Site"
      summary: "The doorlock with the provided device id."
      description: "Get the door lock and it's status."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
        - name: device_id
          in: path
          description: device Id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Successful get doorlocks operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  doorState:
                    type: string
                  lockState:
                    type: string
    put:
      operationId: "api.doorlocks.put_device_from_site"
      tags:
        - "Door Locks Site"
      summary: "Update or create a door lock."
      description: "Update or create the name of the door lock."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
        - name: device_id
          in: path
          description: device Id
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string

      responses:
        "200":
          description: "Successful put doorlocks operation"


  /doorlocks/{site_id}/{device_id}/action:
    get:
      summary: "Returns all the actionfor the provided device id."
      operationId: "api.doorlocks.get_doorlock_actions"
      tags:
        - "Door Locks Site"
      description: "Returns all actions for the door lock."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
        - name: device_id
          in: path
          description: device Id
          required: true
          schema:
            type: string

      responses:
        "200":
          description: "Successful get doorlocks actions operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  datetime:
                    type: string
                  action:
                    type: string
                  message:
                    type: string
                  source:
                    type: string
    
    post:
      summary: "Executes an action for the provided device id."
      operationId: "api.doorlocks.post_doorlock_action"
      tags:
        - "Door Locks Site"
      description: "Executes an action for the door lock."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
        - name: device_id
          in: path
          description: device Id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
      responses:
        "200":
          description: "Successful post doorlocks action"

  /doorlocks/{site_id}/{device_id}/event:
    get:
      summary: "Returns all the events for the provided device id."
      operationId: "api.doorlocks.get_doorlock_events"
      tags:
        - "Door Locks Site"
      description: "Returns all events for the door lock."
      parameters:
        - name: site_id
          in: path
          description: site Id
          required: true
          schema:
            type: string
        - name: device_id
          in: path
          description: device Id
          required: true
          schema:
            type: string

      responses:
        "200":
          description: "Successful get doorlocks actions operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  datetime:
                    type: string
                  event:
                    type: string
                  message:
                    type: string

servers:
  - url: /
