
#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: docker
  containers.ids:
    - '*'

- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*-json.log
  tags: ["docker-logs"]
  processors:
  - add_docker_metadata: ~

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#----------------------------- Elasticsearch Output --------------------------------
output.elasticsearch:
  hosts: ["ELASTICSEARCH_HOST_PORT"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#----------------------------- Kibana Output --------------------------------
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"


#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
- add_host_metadata: ~
- add_docker_metadata: ~
- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true


logging.json: true
logging.metrics.enabled: false


# ================================= Dashboards =================================

# These settings control loading the sample dashboards to the Kibana index.
setup.dashboards.enabled: true