#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#----------------------------- Elasticsearch Output --------------------------------
output.elasticsearch:
  hosts: ["ELASTICSEARCH_HOST_PORT"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"

#----------------------------- Kibana Output --------------------------------
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"



#================================ Modules =====================================

# Configure modules

#----------------------------- Metricbeat Modules --------------------------------
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
    #- "network_summary"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


# ================================= Dashboards =================================

# These settings control loading the sample dashboards to the Kibana index.
setup.dashboards.enabled: true