version: "3.8"
services:
  doorlock-cloud-api:
    build: ./door_lock_cloud_api/
    ports:
      - "5004:5001"
    restart: always
    depends_on:
      - "mqtt-broker"
      - "doorlock-database"

  mqtt-broker:
    build: ./mqtt_broker/
    ports:
      - "1885:1883"
      - "9001:9001"
      - "18083:18083"
      - "4369:4369"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

  doorlock-database:
    build: ./door_lock_database/
    ports: 
      - "6379:6379"
    volumes:
      - redis-volume:/data


#Elastic Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_CLUSTER_NAME: ${ELASTIC_CLUSTER_NAME}
      ELASTIC_NODE_NAME: ${ELASTIC_NODE_NAME}
      ELASTIC_INIT_MASTER_NODE: ${ELASTIC_INIT_MASTER_NODE}
      ELASTIC_DISCOVERY_SEEDS: ${ELASTIC_DISCOVERY_SEEDS}
    ports:
      - 9200:9200
    volumes:
      - ${ELASTIC_DATA}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${ELASTIC_DATA}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    volumes:
      - ${ELASTIC_DATA}/kibana/config:/usr/share/kibana/config
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    user: root
    #if we use docker container logs
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      KIBANA_HOST: ${KIBANA_HOST}
      KIBANA_PORT: ${KIBANA_PORT}
    volumes:
      - ${ELASTIC_DATA}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kibana
  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION}
    user: root
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      KIBANA_HOST: ${KIBANA_HOST}
      KIBANA_PORT: ${KIBANA_PORT}
    volumes:
      - ${ELASTIC_DATA}/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kibana

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log
  redis-volume:
    name: redis-volume
