version: "3.8"
services:
    doorlock-cloud-api:
        build: ../door_lock_cloud_api/
        ports:
        - "5001:5001"
        restart: always
        depends_on:
          - "mqtt-broker"

    mqtt-broker:
        build: ../mqtt_broker/
        ports:
            - "1883:1883"
            - "9001:9001"
            - "18083:18083"
            - "4369:4369"
        volumes:
            - vol-emqx-data:/opt/emqx/data
            - vol-emqx-etc:/opt/emqx/etc
            - vol-emqx-log:/opt/emqx/log

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log